name: Solidity

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  contracts-build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Build contracts
        run: yarn build

      - name: Run tests
        run: yarn test

      - name: Run system tests
        env:
          FORKING_URL: ${{ secrets.MAINNET_ETH_HOSTNAME }}
        run: yarn test:system

  contracts-deployment-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Deploy contracts
        run: yarn deploy

  contracts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

  contracts-slither:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "12.x"
          cache: "yarn"

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8.5

      - name: Install Solidity
        env:
          SOLC_VERSION: 0.8.4 # according to solidity.version in hardhat.config.ts
        run: |
          pip3 install solc-select
          solc-select install $SOLC_VERSION
          solc-select use $SOLC_VERSION

      - name: Install Slither
        env:
          SLITHER_VERSION: 0.8.0
        run: pip3 install slither-analyzer==$SLITHER_VERSION

      - name: Install dependencies
        run: yarn install

      - name: Run Slither
        run: slither .
