name: Solidity

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment for workflow execution"
        required: false
        default: "dev"
      upstream_builds:
        description: "Upstream builds"
        required: false
      upstream_ref:
        description: "Git reference to checkout (e.g. branch name)"
        required: false
        default: "main"

jobs:
  contracts-deployment-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Build contracts
        run: yarn build
      
      - name: Resolve latest contracts
        run: |
          yarn add \
            @keep-network/keep-core \
            @keep-network/tbtc

      - name: Deploy contracts
        env:
          CHAIN_API_URL: ${{ secrets.KEEP_TEST_ETH_HOSTNAME_HTTP }}
          CONTRACT_OWNER_ACCOUNT_PRIVATE_KEY: ${{ secrets.KEEP_TEST_ETH_CONTRACT_OWNER_PRIVATE_KEY }}
        run: yarn deploy --network ropsten

    # TODO: investigate why this works here and not in the original project...!!!
    #  zmien parametry
      - name: Push contracts to Tenderly
        uses: keep-network/tenderly-push-action@v1
        continue-on-error: true
        with:
          tenderly-token: ${{ secrets.TENDERLY_TOKEN }}
          tenderly-project: dimpar/cov-pool-test
          eth-network-id: "3"
          github-project-name: coverage-pools-test
          version-tag: ${{ steps.npm-version-bump.outputs.version }}

